source("week4.R")
print(best("NY","heart attack"))
print(best("TX","heart attack"))
print(best("TX","heart failure"))
print(best("MD","heart attack"))
print(best("MD","pneumonia"))
print(best("BB","pneumonia"))
print(best("NY","plneumonia"))
print(best("XY","heart attack"))
